n = input('Digite algo: ')
print('='*40)
print(f'Texto digitado: {n}')
print('='*40)
print('O tipo primitivo armazenado é: ',type(n))
print('É alfanumérico?:', n.isalnum())
print('É um número?:', n.isnumeric())
print('É/São caractere(s) alfabético(s)?:', n.isalpha())
#print('é um ???:', n.index(sub))
print('É ASCII?:', n.isascii())
print('É Decimal?:', n.isdecimal())
print('É um dígt string???:', n.isdigit())
print('É um identificador válido do py??:', n.isidentifier())
print('Está em minúsculo?:', n.islower())
print('Está em MAIÚSCULO?:', n.isupper())
print('É imprimível?:', n.isprintable())
print('É espaço em branco?:', n.isspace())
print('Está Capitalizada?:', n.istitle())